In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./test.csv", dtype="string")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  string
 1   status                 584509 non-null  string
 2   created_at             584524 non-null  string
 3   sku                    584504 non-null  string
 4   price                  584524 non-null  string
 5   qty_ordered            584524 non-null  string
 6   grand_total            584524 non-null  string
 7   increment_id           584524 non-null  string
 8   category_name_1        584360 non-null  string
 9   sales_commission_code  447346 non-null  string
 10  discount_amount        584524 non-null  string
 11  payment_method         584524 non-null  string
 12  Working Date           584524 non-null  string
 13  BI Status              584524 non-null  string
 14   MV                    584524 non-null  string
 15  Year                   584524 non-null  string
 16  Month                  584524 non-null  string
 17  Customer Since         584513 non-null  string
 18  M-Y                    584524 non-null  string
 19  FY                     584524 non-null  string
 20  Customer ID            584513 non-null  string
 21  Unnamed: 21            0 non-null       string
 22  Unnamed: 22            0 non-null       string
 23  Unnamed: 23            0 non-null       string
 24  Unnamed: 24            0 non-null       string
 25  Unnamed: 25            0 non-null       string
dtypes: string(26)
memory usage: 284.0 MB

#### 1.1) Проверка и очистка датасета

Проверим корректность существующих столбцов. Заметим, что есть лишние пробелы в названиях столбцов, а также пустые столбцы, которые не содержат в себе данных.

In [4]:
df.head()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131,complete,7/1/2016,kreations_YI 06-L,1950,1,1950,100147443,Women's Fashion,\N,...,7,2016-7,7-2016,FY17,1,<NA>,<NA>,<NA>,<NA>,<NA>
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240,1,240,100147444,Beauty & Grooming,\N,...,7,2016-7,7-2016,FY17,2,<NA>,<NA>,<NA>,<NA>,<NA>
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450,1,2450,100147445,Women's Fashion,\N,...,7,2016-7,7-2016,FY17,3,<NA>,<NA>,<NA>,<NA>,<NA>
3,211135,complete,7/1/2016,kcc_krone deal,360,1,60,100147446,Beauty & Grooming,R-FSD-52352,...,7,2016-7,7-2016,FY17,4,<NA>,<NA>,<NA>,<NA>,<NA>
4,211136,order_refunded,7/1/2016,BK7010400AG,555,2,1110,100147447,Soghaat,\N,...,7,2016-7,7-2016,FY17,5,<NA>,<NA>,<NA>,<NA>,<NA>

In [5]:
df.columns = df.columns.str.strip()

In [6]:
cols = [
    "Unnamed: 21",
    "Unnamed: 22",
    "Unnamed: 23",
    "Unnamed: 24",
    "Unnamed: 25"
]
print(df[cols].isna().all())

Unnamed: 21    True
Unnamed: 22    True
Unnamed: 23    True
Unnamed: 24    True
Unnamed: 25    True
dtype: bool

In [7]:
df = df.drop(columns=cols)

print("Удалены:", cols)

Удалены: ['Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']

In [8]:
for col in df.columns:
    print(f"Столбец {col}: {df[col].isna().all()}")

Столбец item_id: False
Столбец status: False
Столбец created_at: False
Столбец sku: False
Столбец price: False
Столбец qty_ordered: False
Столбец grand_total: False
Столбец increment_id: False
Столбец category_name_1: False
Столбец sales_commission_code: False
Столбец discount_amount: False
Столбец payment_method: False
Столбец Working Date: False
Столбец BI Status: False
Столбец MV: False
Столбец Year: False
Столбец Month: False
Столбец Customer Since: False
Столбец M-Y: False
Столбец FY: False
Столбец Customer ID: False

Все остальные столбцы не являются полностью пустыми и, вероятно, содержат в себе какую-то содержательную информацию, которую нужно изучить.

#### 1.2) Проверка и приведение типов данных:

In [9]:
df.columns

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'Working Date', 'BI Status', 'MV', 'Year', 'Month', 'Customer Since',
       'M-Y', 'FY', 'Customer ID'],
      dtype='str')

##### 1.2.1) Проверка для идентификаторов: 'item_id', 'increment_id', 'sku', 'Customer ID', 'sku'

Некоторые столбцы содержат в себе значение "\N", которое означает отсутствующие данные. Такие значения заменим на pd.NA.

In [10]:
id_cols = [
    "item_id",
    "increment_id",
    "Customer ID",
    "sku",
    "sales_commission_code"
]

for col in id_cols:
    s = df[col]
    s = s.str.strip()
    s = s.replace(r"\N", pd.NA)

    print(f"\n--- {col} ---")
    print("Пропусков:", s.isna().sum())
    df[col] = df[col].astype("string").str.strip()
    print("Уникальных значений:", s.nunique(dropna=True))
    print("Повторяющихся значений:",
          s[s.notna()].duplicated().sum())

    df[col] = s

--- item_id ---
Пропусков: 464051
Уникальных значений: 584524
Повторяющихся значений: 0

--- increment_id ---
Пропусков: 464051
Уникальных значений: 408782
Повторяющихся значений: 175742

--- Customer ID ---
Пропусков: 464062
Уникальных значений: 115326
Повторяющихся значений: 469187

--- sku ---
Пропусков: 464071
Уникальных значений: 84799
Повторяющихся значений: 499705

--- sales_commission_code ---
Пропусков: 940230
Уникальных значений: 7193
Повторяющихся значений: 101152

##### 1.2.2) Проверка для числовых данных: 'price', 'qty_ordered', 'grand_total', 'discount_amount', 'MV'

In [11]:
numeric_cols = [
    "price",
    "qty_ordered",
    "grand_total",
    "discount_amount",
    "MV"
]

for col in numeric_cols:
    numeric = pd.to_numeric(df[col], errors="coerce")

    bad_mask = df[col].notna() & numeric.isna()

    print(f"\n--- {col} ---")
    print("Некорректных:", bad_mask.sum())
    print("Пропусков:", df[col].isna().sum())
    print("Нулевых:", (numeric == 0).sum())
    print("Отрицательных:", (numeric < 0).sum())

--- price ---
Некорректных: 0
Пропусков: 464051
Нулевых: 2232
Отрицательных: 0

--- qty_ordered ---
Некорректных: 0
Пропусков: 464051
Нулевых: 0
Отрицательных: 0

--- grand_total ---
Некорректных: 0
Пропусков: 464051
Нулевых: 9632
Отрицательных: 76

--- discount_amount ---
Некорректных: 0
Пропусков: 464051
Нулевых: 376306
Отрицательных: 3

--- MV ---
Некорректных: 291588
Пропусков: 464051
Нулевых: 40
Отрицательных: 0

In [12]:
mv_num = pd.to_numeric(df["MV"], errors="coerce")
bad_mask = df["MV"].notna() & mv_num.isna()
df.loc[bad_mask, "MV"].value_counts().head(20)

MV
1,000      6895
2,000      4499
1,999      3883
12,599     3797
2,500      3560
5,000      3117
1,200      3110
1,500      2947
13,698     2733
14,000     2689
4,000      2609
1,499      2539
3,000      2454
-          2232
1,099      2127
1,199      2123
22,999     1795
17,160     1679
1,050      1577
1,299      1567
Name: count, dtype: int64[pyarrow]

Заметим, что здесь используется разделитель в виде запятой. Изначально я предположила, что он используется как разделитель дробной и целой части, но в данных присутствовали значения вида "1,000,000", поэтому запятая используется как разделитель тысяч. Также заметим, что здесь присутствуют пропуски в данных, отмеченные символом "-".

In [13]:
mv_clean = (
    df["MV"]
    .astype("string")
    .str.strip()
    .str.replace(",", "", regex=False)
)

mv_clean = mv_clean.replace("-", pd.NA)

mv_num = pd.to_numeric(mv_clean, errors="coerce")
bad_mask = mv_clean.notna() & mv_num.isna()

print("Некорректных после очистки:", bad_mask.sum())
print(
    mv_clean[bad_mask]
    .value_counts()
    .head(20)
)

Некорректных после очистки: 0
Series([], Name: count, dtype: int64[pyarrow])

Проверка подходит, поэтому можем выполнить её на целом датасете.

In [14]:
df["MV"] = (
    df["MV"]
    .astype("string")
    .str.strip()
    .str.replace(",", "", regex=False)
    .replace("-", pd.NA)
)

df["MV"] = pd.to_numeric(df["MV"], errors="coerce")

In [15]:
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

##### 1.2.3) Проверка столбцов с категориальными данными: 'status', 'category_name_1', 'payment_method', 'BI Status'

In [16]:
categorical_cols = [
    "status",
    "category_name_1",
    "payment_method",
    "BI Status"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- status ---
status
<NA>              464066
complete          233685
canceled          201249
received           77290
order_refunded     59529
refund              8050
cod                 2859
paid                1159
closed               494
payment_review        57
pending               48
processing            33
holded                31
fraud                 10
pending_paypal         7
exchange               4
\N                     4
Name: count, dtype: int64[pyarrow]

--- category_name_1 ---
category_name_1
<NA>                  464215
Mobiles & Tablets     115710
Men's Fashion          92221
Women's Fashion        59721
Appliances             52413
Superstore             43613
Beauty & Grooming      41496
Soghaat                34011
Others                 29218
Home & Living          26504
Entertainment          26326
Health & Sports        17502
Kids & Baby            16494
Computing              15933
\N                      7850
School & Education      3478
Books                   1870
Name: count, dtype: int64[pyarrow]

--- payment_method ---
payment_method
<NA>                 464051
cod                  271960
Payaxis               97641
Easypay               82900
jazzwallet            35145
easypay_voucher       31176
bankalfalah           23065
jazzvoucher           15633
Easypay_MA            14028
customercredit         7555
apg                    1758
ublcreditcard           882
cashatdoorstep          732
mcblite                 723
mygateway               669
internetbanking         472
productcredit           125
marketingexpense         45
financesettlement        15
Name: count, dtype: int64[pyarrow]

--- BI Status ---
BI Status
<NA>     464051
Net      234178
Gross    201454
Valid    148891
#REF!         1
Name: count, dtype: int64[pyarrow]

Заметим, что здесь также встречается "\N", а также "#REF!" - это, скорее всего, значение из Excel, содержащее некорректную ссылку. Заменим это значение на отсутствующее.

In [17]:
df["status"] = df["status"].replace(r"\N", pd.NA)
df["category_name_1"] = df["category_name_1"].replace(r"\N", pd.NA)
df["BI Status"] = df["BI Status"].replace("#REF!", pd.NA)

##### 1.2.4) Проверка столбцов для записи дат: 'created_at', 'Working Date', 'Customer Since'

In [18]:
date_cols = [
    "created_at",
    "Working Date",
    "Customer Since"
]

for col in date_cols:
    parsed = pd.to_datetime(df[col], errors="coerce")

    bad_mask = df[col].notna() & parsed.isna()

    print(f"\n--- {col} ---")
    print("Некорректных дат:", bad_mask.sum())
    print("Пропусков:", df[col].isna().sum())
    print("Минимальная дата:", parsed.min())
    print("Максимальная дата:", parsed.max())

--- created_at ---
Некорректных дат: 0
Пропусков: 464051
Минимальная дата: 2016-07-01 00:00:00
Максимальная дата: 2018-08-28 00:00:00

--- Working Date ---
Некорректных дат: 0
Пропусков: 464051
Минимальная дата: 2016-07-01 00:00:00
Максимальная дата: 2018-08-28 00:00:00

--- Customer Since ---
Некорректных дат: 0
Пропусков: 464062
Минимальная дата: 2016-07-01 00:00:00
Максимальная дата: 2018-08-01 00:00:00

In [19]:
df["created_at"] = pd.to_datetime(
    df["created_at"],
    errors="coerce"
)
df["Working Date"] = pd.to_datetime(
    df["Working Date"],
    errors="coerce"
)

df["Customer Since"] = pd.to_datetime(
    df["Customer Since"],
    errors="coerce"
)

##### 1.2.5) Проверка производных от даты столбцов: 'Year', 'Month', 'M-Y', 'FY'

In [20]:
derived_date_cols = [
    "Year",
    "Month",
    "M-Y",
    "FY"
]

for col in derived_date_cols:
    print(f"\n--- {col} ---")
    print("Пропусков:", df[col].isna().sum())
    print("Уникальных:", df[col].nunique(dropna=True))
    print(df[col].value_counts(dropna=False).head(20))

--- Year ---
Пропусков: 464051
Уникальных: 3
Year
<NA>    464051
2017    290920
2018    159695
2016    133909
Name: count, dtype: int64[pyarrow]

--- Month ---
Пропусков: 464051
Уникальных: 12
Month
<NA>    464051
11      155456
5        62603
3        61489
8        48514
7        39151
2        38777
6        34530
4        34091
10       30623
12       29199
1        26067
9        24024
Name: count, dtype: int64[pyarrow]

--- M-Y ---
Пропусков: 464051
Уникальных: 26
M-Y
<NA>       464051
11-2017     83928
11-2016     71528
3-2018      41955
5-2017      34736
5-2018      27867
2-2018      26916
8-2017      25083
4-2017      21678
6-2017      19793
3-2017      19534
7-2017      19275
10-2017     17499
12-2017     15747
9-2016      15433
6-2018      14737
12-2016     13452
1-2017      13195
10-2016     13124
1-2018      12872
Name: count, dtype: int64[pyarrow]

--- FY ---
Пропусков: 464051
Уникальных: 3
FY
<NA>    464051
FY18    306883
FY17    254706
FY19     22935
Name: count, dtype: int64[pyarrow]

Проверим, что они совпадают с Working Date.

In [21]:
year_num = pd.to_numeric(df["Year"], errors="coerce")

mask_year_mismatch = (
    df["Working Date"].notna()
    & year_num.notna()
    & (year_num != df["Working Date"].dt.year)
)

print("Несоответствий Year:", mask_year_mismatch.sum())

Несоответствий Year: 0

In [22]:
month_num = pd.to_numeric(df["Month"], errors="coerce")

mask_month_mismatch = (
    df["Working Date"].notna()
    & month_num.notna()
    & (month_num != df["Working Date"].dt.month)
)

print("Несоответствий Month:", mask_month_mismatch.sum())

Несоответствий Month: 0

In [23]:
expected_my = (
    df["Working Date"].dt.month.astype("Int64").astype("string")
    + "-"
    + df["Working Date"].dt.year.astype("Int64").astype("string")
)

mask_my_mismatch = (
    df["Working Date"].notna()
    & df["M-Y"].notna()
    & (df["M-Y"].astype("string") != expected_my)
)

print("Несоответствий M-Y:", mask_my_mismatch.sum())

Несоответствий M-Y: 0

In [24]:
df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")
df["Month"] = pd.to_numeric(df["Month"], errors="coerce").astype("Int64")

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  string
 1   status                 584505 non-null  string
 2   created_at             584524 non-null  datetime64[us]
 3   sku                    584504 non-null  string
 4   price                  584524 non-null  Float64
 5   qty_ordered            584524 non-null  Int64
 6   grand_total            584524 non-null  Float64
 7   increment_id           584524 non-null  string
 8   category_name_1        576510 non-null  string
 9   sales_commission_code  108345 non-null  string
 10  discount_amount        584524 non-null  Float64
 11  payment_method         584524 non-null  string
 12  Working Date           584524 non-null  datetime64[us]
 13  BI Status              584523 non-null  string
 14  MV                     582292 non-null  Int64
 15  Year                   584524 non-null  Int64
 16  Month                  584524 non-null  Int64
 17  Customer Since         584513 non-null  datetime64[us]
 18  M-Y                    584524 non-null  string
 19  FY                     584524 non-null  string
 20  Customer ID            584513 non-null  string
dtypes: Float64(3), Int64(4), datetime64[us](3), string(11)
memory usage: 222.9 MB

#### 1.3) Удаление пустых или малоинформативных строк

In [26]:
print("Полностью пустых строк:", df.isna().all(axis=1).sum())
df = df.dropna(how="all").copy()

Полностью пустых строк: 464051

In [27]:
non_null_count = df.notna().sum(axis=1)

print("Строк с 0 заполненных полей:", (non_null_count == 0).sum())
print("Строк с 1 заполненным полем:", (non_null_count == 1).sum())
print("Строк с 2 заполненными полями:", (non_null_count == 2).sum())

Строк с 0 заполненных полей: 0
Строк с 1 заполненным полем: 0
Строк с 2 заполненными полями: 0

In [28]:
df.head()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,2016-07-01,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,<NA>,...,cod,2016-07-01,<NA>,1950,2016,7,2016-07-01,7-2016,FY17,1
1,211133,canceled,2016-07-01,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,<NA>,...,cod,2016-07-01,Gross,240,2016,7,2016-07-01,7-2016,FY17,2
2,211134,canceled,2016-07-01,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,<NA>,...,cod,2016-07-01,Gross,2450,2016,7,2016-07-01,7-2016,FY17,3
3,211135,complete,2016-07-01,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,2016-07-01,Net,360,2016,7,2016-07-01,7-2016,FY17,4
4,211136,order_refunded,2016-07-01,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,<NA>,...,cod,2016-07-01,Valid,1110,2016,7,2016-07-01,7-2016,FY17,5

1.4) Запись изменений в новый файл

In [29]:
df.to_parquet("./cleaned_types.parquet", index=False)